FROM php:8.3-cli AS builder

RUN apt-get update && apt-get install -y unzip

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json ./
RUN composer install --no-interaction

COPY . .


FROM php:8.3-fpm-alpine

WORKDIR /app

COPY --from=builder /app/vendor ./vendor
COPY --from=builder /app/index.php ./index.php
